spring:
  application:
    name: Washer-Backend-v2
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      poolName: washerPool
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: -1ms
  security:
    cors:
      allowed-origins:
        - 'http://localhost:3000'
        - 'http://localhost:3001'
  docker:
    compose:
      enabled: false
reservation:
  disable-time-restriction: true
sdk:
  logging:
    enabled: true
    not-logging-urls:
      - "/v3/api-docs/**"
      - "/swagger-ui/**"
  swagger:
    enabled: true
    title: "Washer API"
    description: "기숙사 세탁기 예약 관리 시스템"
    version: "v2"
    group: "Washer"
    paths-to-match:
      - "/api/v2/**"
  exception:
    enabled: false
  response:
    enabled: true
    not-wrapping-urls:
      - "/v3/api-docs/**"
      - "/v3/api-docs"
      - "/swagger-ui/**"
      - "/api/v2/admin/smartthings/oauth/authorize"
logging:
  level:
    team.washer.server.v2.domain.smartthings: INFO
    org.springframework.security: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
server:
  port: 8080
  shutdown: graceful
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600
  refresh-token-expiration: 2592000
third-party:
  discord:
    webhook-url: ${THIRD_PARTY_DISCORD_WEBHOOK_URL}
  datagsm:
    client-secret: ${THIRD_PARTY_DATAGSM_CLIENT_SECRET}
    client-id: ${THIRD_PARTY_DATAGSM_CLIENT_ID}
    redirect-uri: ${THIRD_PARTY_DATAGSM_REDIRECT_URI}
  smartthings:
    api-url: ${THIRD_PARTY_SMARTTHINGS_API_URL:https://api.smartthings.com}
    oauth-url: ${THIRD_PARTY_SMARTTHINGS_OAUTH_URL:https://api.smartthings.com/oauth/token}
    authorize-url: ${THIRD_PARTY_SMARTTHINGS_AUTHORIZE_URL:https://api.smartthings.com/oauth/authorize}
    redirect-uri: ${THIRD_PARTY_SMARTTHINGS_REDIRECT_URI}
    client-id: ${THIRD_PARTY_SMARTTHINGS_CLIENT_ID}
    client-secret: ${THIRD_PARTY_SMARTTHINGS_CLIENT_SECRET}
    operation-schedule:
      enabled: ${THIRD_PARTY_SMARTTHINGS_OPERATION_SCHEDULE_ENABLED:false}
springdoc:
  swagger-ui:
    enabled: true
