name: Washer Prod CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Prod-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: zulu
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Code Format Check
        run: ./gradlew spotlessCheck --no-daemon

      - name: Notify CI Success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0x4CAF50

      - name: Notify CI Failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0xFF4C4C

      - name: Notify CI Cancelled
        uses: sarisia/actions-status-discord@v1
        if: cancelled()
        with:
          webhook: ${{ secrets.DISCORD_INFORMATION_ALERT_CHANNEL_WEBHOOK }}
          color: 0xFF4C4C